monolog:
  channels: ["app"]
  handlers:
    main:
      type: stream
      path: "%kernel.project_dir%/var/log/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.project_dir%/var/log/%kernel.environment%.log"
        level: debug
        channels: ["!event"]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]
      # uncomment to get logging in your browser
      # you may have to allow bigger header sizes in your Web server configuration
      firephp:
        type: firephp
        level: info
      chromephp:
        type: chromephp
        level: info

when@test:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.project_dir%/var/log/%kernel.environment%.log"
        level: debug
        channels: ["!event"]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
      nested:
        type: stream
        path: php://stderr
        level: debug
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
